FETCHED_PAGES_DIR_NAME = '917' #参照ディレクトリ
QUERY = 'sixteen' #分類(参照ファイルと同じ名前じゃないとダメ？)
#QUERIES = '胃もたれ 虫歯 花粉症対策 鬱 機械 骨折 肩こり 書類'.split(' ')←無視していい
QUERIES = 'sixteen'.split(' ') #参照ファイル
NUM_OF_FETCHED_PAGES = 50
NB_PKL_FILENAME = 'naive_bayes_classifier.pkl'
MIN_DF = 0.0001
MAX_DF = 0.5
DOC_NUM = 0
MIN_TFIDF = 0.1
TFIDF_RESULT_PKL_FILENAME = 'tfidf_result.pkl'
TFIDF_VECTORIZER_PKL_FILENAME = 'tfidf_vectorizer.pkl'
